In [6]:
# Fancy indexing

import numpy as np

arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr1)

# select elelments from the array
print(arr1[[1, 2, 5, 7]])


print("-" * 60)
# simple indexing
print(arr1[3])

print("-" * 60)
print(arr1[[7, 3, 0, 4]])



[1 2 3 4 5 6 7 8]
[2 3 6 8]
------------------------------------------------------------
4
------------------------------------------------------------
[8 4 1 5]


In [10]:
# sorting an numpy array

arr1 = np.array([3, 8, 1, 5, 7, 2, 4, 6])
print(arr1)

# sort the given array in ascending order
print("-" * 60)
res = arr1[np.argsort(arr1)]
print(res)

# sort the given array in descending order
print("-" * 60)
res = arr1[np.argsort(-arr1)]
print(res)



[3 8 1 5 7 2 4 6]
------------------------------------------------------------
[1 2 3 4 5 6 7 8]
------------------------------------------------------------
[8 7 6 5 4 3 2 1]


In [15]:
arr1 = np.array([3, 8, 1, 5, 7, 2, 4, 6])
print(arr1)

print("-" * 60)
indices = [1, 6, 2, 4]

new_val = [80, 40, 10, 70]

print(arr1[indices])

arr1[indices] = new_val
print("-" * 60)

print(arr1)

[3 8 1 5 7 2 4 6]
------------------------------------------------------------
[8 4 1 7]
------------------------------------------------------------
[ 3 80 10  5 70  2 40  6]


In [19]:
# n-dimension array

arr1 = np.array([[1, 2, 3], 
                 [4, 5, 6], 
                 [7, 8, 9]])

print(arr1)

row_ind = np.array([0, 2])
print("-" * 60)

sel_rows = arr1[row_ind, :]
print(sel_rows)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
------------------------------------------------------------
[[1 2 3]
 [7 8 9]]
