In [5]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

# + operator

print(f"arr1 :{arr1}")
print(f"arr2 :{arr2}")

print("-" * 60)
arr3 = arr1 + arr2

print(f"arr3 :{arr3}")

print("-" * 60)
arr4 = np.add(arr1, arr2)

print(f"arr4 :{arr4}")


arr1 :[1 2 3 4 5]
arr2 :[ 6  7  8  9 10]
------------------------------------------------------------
arr3 :[ 7  9 11 13 15]
------------------------------------------------------------
arr4 :[ 7  9 11 13 15]


In [9]:
arr1 = np.array([10, 11, 12, 13, 14])
arr2 = np.array([4, 5, 6, 7, 8])

print(f"arr1 :{arr1}")
print(f"arr2 :{arr2}")

# - operator
print("-" * 60)
arr3 = arr1 - arr2
print(f"arr3 :{arr3}")

print("-" * 60)
arr4 = np.subtract(arr1, arr2)

print(f"arr4 :{arr4}")


arr1 :[10 11 12 13 14]
arr2 :[4 5 6 7 8]
------------------------------------------------------------
arr3 :[6 6 6 6 6]
------------------------------------------------------------
arr4 :[6 6 6 6 6]


In [14]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([2, 4, 6, 8 ,10])

print(f"arr1 :{arr1}")
print(f"arr2 :{arr2}")

print("-" * 60)
arr3 = arr1 * arr2
print(f"arr3 :{arr3}")

print("-" * 60)
arr4 = np.multiply(arr1, arr2)
print(f"arr4 :{arr4}")




arr1 :[1 2 3 4 5]
arr2 :[ 2  4  6  8 10]
------------------------------------------------------------
arr3 :[ 2  8 18 32 50]
------------------------------------------------------------
arr4 :[ 2  8 18 32 50]


In [19]:
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([1, 2, 3, 4, 5])

print(f"arr1 :{arr1}")
print(f"arr2 :{arr2}")

print("-" * 60)
arr3 = arr1 / arr2
print(f"arr3 :{arr3}")

print("-" * 60)
arr4 = np.divide(arr1, arr2)
print(f"arr4 :{arr4}")
      

arr1 :[10 20 30 40 50]
arr2 :[1 2 3 4 5]
------------------------------------------------------------
arr3 :[10. 10. 10. 10. 10.]
------------------------------------------------------------
arr4 :[10. 10. 10. 10. 10.]


In [22]:
arr1 = np.array([1, 2, 3, 4, 5])
print(f"arr1 :{arr1}")

print("-" * 60)
arr2 = arr1 ** 2
print(f"arr2 :{arr2}")


arr1 :[1 2 3 4 5]
------------------------------------------------------------
arr2 :[ 1  4  9 16 25]


In [28]:
arr1 = np.array([10, 20, 30])
arr2 = np.array([3, 4, 7])

print(f"arr1 :{arr1}")
# % operator
print("-" * 60)
arr3 = arr1 % arr2
print(f"arr3 :{arr3}")

print("-" * 60)
arr4 = np.mod(arr1, arr2)

print(f"arr4 :{arr4}")

arr1 :[10 20 30]
------------------------------------------------------------
arr3 :[1 0 2]
------------------------------------------------------------
arr4 :[1 0 2]


In [33]:
# array creation Functions

arr1 = np.array([1, 2, 3, 4, 5])
print(f"np.array() :{arr1}")

print("-" * 60)

arr2 = np.zeros([3, 3])
print(f"np.zeros() :\n{arr2}")

print("-" * 60)

arr3 = np.ones([2, 4])
print(f"np.ones() :\n{arr3}")

np.array() :[1 2 3 4 5]
------------------------------------------------------------
np.zeros() :
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
------------------------------------------------------------
np.ones() :
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [40]:
# array manipulation  functions

arr1 = np.array([2, 4, 6, 7, 8, 10])
print(f"arr1 :{arr1}")

print("-" * 60)
arr2 = np.reshape(arr1, (2, 3))
print(f"arr2 :\n{arr2}")

print("-" * 60)
arr3 = np.reshape(arr2, (3, 2))
print(f"arr3 :\n{arr3}")

print("-" * 60)
arr4 = np.transpose(arr2)
print(f"arr4 :\n{arr4}")



arr1 :[ 2  4  6  7  8 10]
------------------------------------------------------------
arr2 :
[[ 2  4  6]
 [ 7  8 10]]
------------------------------------------------------------
arr3 :
[[ 2  4]
 [ 6  7]
 [ 8 10]]
------------------------------------------------------------
arr4 :
[[ 2  7]
 [ 4  8]
 [ 6 10]]


In [44]:
# array Mathematical fnctions

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([4, 9, 16, 25, 36])

print(f"arr1 :{arr1}")
print(f"arr2 :{arr2}")

print("-" * 60)
# Addition
arr3 = np.add(arr1, arr2)
print(f"arr3 :{arr3}")

print("-" * 60)
# Subtract
arr4 = np.subtract(arr2, arr1)
print(f"arr4 :{arr4}")

print("-" * 60)
# sqrt function
arr5 = np.sqrt(arr2)
print(f"arr5 :{arr5}")


arr1 :[1 2 3 4 5]
arr2 :[ 4  9 16 25 36]
------------------------------------------------------------
arr3 :[ 5 11 19 29 41]
------------------------------------------------------------
arr4 :[ 3  7 13 21 31]
------------------------------------------------------------
arr5 :[2. 3. 4. 5. 6.]


In [53]:
# Statiscal Functions

marks = np.array([76, 82, 87, 60, 93])
print(f"marks :{marks}")

# Mean
print("-" * 60)
arr2 = np.mean(marks)
print(f"arr2 :{arr2}")

# median
print("-" * 60)
arr3 = np.median(marks)
print(f"arr3 :{arr3}")

# Max and Min
print("-" * 60)
min_val = np.min(marks)
print(f"Minimum Value :{min_val}")

print("-" * 60)
max_val = np.max(marks)
print(f"Maximum Value :{max_val}")
    

marks :[76 82 87 60 93]
------------------------------------------------------------
arr2 :79.6
------------------------------------------------------------
arr3 :82.0
------------------------------------------------------------
Minimum Value :60
------------------------------------------------------------
Maximum Value :93


In [62]:
# input and output functions

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
print(F"arr1 :\n{arr1}")
np.savetxt("C:/Users/Kiran/CDAC/myarray.txt", arr1)

print("-" * 60)

arr2 = np.loadtxt("C:/Users/Kiran/CDAC/myarray.txt")
print(f"arr2 :\n{arr2}")


arr1 :
[[1 2 3]
 [4 5 6]]
------------------------------------------------------------
arr2 :
[[1. 2. 3.]
 [4. 5. 6.]]
