In [3]:
import numpy as np

print(f"The value if pi :{np.pi}")

print(f"The value of Euler's Constant :{np.e}")

x = 1
y = np.exp(x)
print(f"y :{y}")

The value if pi :3.141592653589793
The value of Euler's Constant :2.718281828459045
y :2.718281828459045


In [4]:
# Standard deviation and Percentile functions

arr1 = np.array([1, 2, 3, 4, 5])

print(f"median :{np.median(arr1)}")

arr2 = np.array([[2, 4, 6], 
                 [8, 10, 12],
                 [14, 16, 18]])

print(f"arr2 :\n{arr2}")

print("-" * 60)

res1 = np.median(arr2, axis=1)
print(f"Median along horizontal Axis :{res1}")

res2 = np.median(arr2, axis=0)
print(f"Median along vertical Axis :{res2}")

res3 = np.median(arr2)
print(f"Median :{res3}")

median :3.0
arr2 :
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
------------------------------------------------------------
Median along horizontal Axis :[ 4. 10. 16.]
Median along vertical Axis :[ 8. 10. 12.]
Median :10.0


In [11]:
# mean function on 2D array

arr1 = np.array([[1, 2],
                 [3, 4]])

print(f"arr1 :\n{arr1}")

res1 = np.mean(arr1)
print(f"Mean is  :{res1}")

print("-" * 60)
# calculate the mean vertical axis
res2 = np.mean(arr1, axis = 0)
print(f"Mean is :{res2}")

print("-" * 60)
# calculate the mean along horzontal axis
res3 = np.mean(arr1, axis = 1)
print(f"Mean is :{res3}")



arr1 :
[[1 2]
 [3 4]]
Mean is  :2.5
------------------------------------------------------------
Mean is :[2. 3.]
------------------------------------------------------------
Mean is :[1.5 3.5]


In [14]:
# standard deviation

marks = np.array([78, 67, 89, 93, 75])
print(f"marks :{marks}")

std_marks = np.std(marks)
print(f"Standard Deviation :{std_marks}")

marks :[78 67 89 93 75]
Standard Deviation :9.457272334029511


In [21]:
# Standard Deviation 2D array

arr1 = np.array([[2, 5, 9], 
                 [3, 8, 11], 
                 [4, 6, 7]])

print(f"arr1 :\n{arr1}")

print('-' * 60)
res1 = np.std(arr1)
print(f"res1 :{res1}")

print('-' * 60)
# vertical
res2 = np.std(arr1, axis = 0)
print(f"std is :{res2}")

print('-' * 60)
# horizontal
res3 = np.std(arr1, axis = 1)
print(f"std is :{res3}")

arr1 :
[[ 2  5  9]
 [ 3  8 11]
 [ 4  6  7]]
------------------------------------------------------------
res1 :2.7666443551086073
------------------------------------------------------------
std is :[0.81649658 1.24721913 1.63299316]
------------------------------------------------------------
std is :[2.86744176 3.29983165 1.24721913]


In [34]:
# precentile

arr1 = np.array([1, 2, 3, 4, 5])
print(f"arr1 :{arr1}")

# calculate the 25th percentile of the array
res1 = np.percentile(arr1, 50)
print(res1)

res1 = np.percentile(arr1, 25)
print(res1)

arr2 = np.array([1, 3, 5, 7, 9, 11, 13, 15, 17, 19])

res3 = np.percentile(arr2, 25)
print(res3)

arr1 :[1 2 3 4 5]
3.0
2.0
5.5


In [39]:
# max and  min functions

arr1  = np.array([22, 6, 9, 15, 17, 22, 65, 10, 62])
print(f"arr1 :{arr1}")

print(f"Min Val :{np.min(arr1)}")

print(f"Max Val :{np.max(arr1)}")



arr1 :[22  6  9 15 17 22 65 10 62]
Min Val :6
Max Val :65
