In [4]:
import numpy as np

arr1 = np.array([[1, 2, 3], 
                 [4, 5, 6]])
print(arr1)

np.save("myfile.npy", arr1)

[[1 2 3]
 [4 5 6]]


In [8]:
# load data saves in numpy array
loaded_array= np.load('myfile.npy')
print([loaded_array])

[array([[1, 2, 3],
       [4, 5, 6]])]


In [11]:
# save to text file 
arr1 = np.array([[1, 4, 5],
                 [6, 7, 8]])

np.savetxt("file3.txt", arr1)


In [17]:
# load from a txt file

arr1 = np.loadtxt("C:\\Users\\Kiran\\file3.txt")

print(arr1)

[[1. 4. 5.]
 [6. 7. 8.]]
